apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-stack.mysql.fullname" . }}
  labels:
{{- include "wordpress-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "wordpress-stack.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mysql
