{{- $dbHost := .Values.wordpress.env.dbHostOverride | default (printf "%s:%d" (include "wordpress-stack.mysql.fullname" .) (int .Values.mysql.service.port)) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress-stack.wordpress.fullname" . }}
  labels:
{{- include "wordpress-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: wordpress
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wordpress-stack.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: wordpress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "wordpress-stack.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: wordpress
    spec:
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: wordpress
          image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}"
          imagePullPolicy: {{ .Values.wordpress.image.pullPolicy }}
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ $dbHost | quote }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.wordpress.env.dbName | quote }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.wordpress.env.dbUser | quote }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.wordpress.env.dbPassword | quote }}
          ports:
            - name: fpm
              containerPort: {{ .Values.wordpress.service.port }}
              protocol: TCP
{{- if .Values.wordpress.persistence.enabled }}
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
{{- end }}
{{- with .Values.wordpress.resources }}
          resources:
{{- toYaml . | nindent 12 }}
{{- end }}
{{- if .Values.wordpress.persistence.enabled }}
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: {{ include "wordpress-stack.wordpress.fullname" . }}
{{- else }}
      volumes:
        - name: wordpress-data
          emptyDir: {}
{{- end }}
{{- with .Values.wordpress.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.wordpress.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.wordpress.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
